create database SQL_PROJECT;

CREATE TABLE EMPLOYEE_DETAIL_TABLE(
EMPLOYEE_ID INT,
FIRSTNAME VARCHAR(50),
LASTNAME VARCHAR(50),
SALARY INT,
JOINING_DATE DATETIME,
DEPARTMENT VARCHAR (20),
GENDER VARCHAR (50))
;

SELECT*FROM EMPLOYEE_DETAIL_TABLE;

INSERT INTO EMPLOYEE_DETAIL_TABLE VALUES
(1, 'VIKAS', 'AHLAWAT', 600000, '2/12/2013 11:16:00', 'IT', 'MALE'),
(2, 'NIKITA', 'JAIN', 530000, '2/14/2013 11:16:00', 'HR', 'FEMALE'),
(3, 'ASHISH', 'KUMAR', 1000000, '2/14/2013 11:16:00', 'IT', 'MALE'),
(4, 'NIKHIL', 'SHARMA', 480000, '2/15/2013 11:16:00', 'HR', 'MALE'),
(5, 'ANISH', 'KADIAN', 500000, '2/16/2013 11:16:00', 'PAROLL', 'MALE');


SELECT * FROM EMPLOYEE_DETAIL_TABLE;------------------------------------1

SELECT FIRSTNAME FROM EMPLOYEE_DETAIL_TABLE; --------------------------------------2

SELECT UPPER(FIRSTNAME) AS FIRST_NAME
FROM EMPLOYEE_DETAIL_TABLE; -----------------------------------3&4

SELECT CONCAT(FIRSTNAME, ' ', LASTNAME) AS NAME
FROM EMPLOYEE_DETAIL_TABLE; ---------------------------------------5

SELECT * FROM EMPLOYEE_DETAIL_TABLE
WHERE FIRSTNAME IN ('VIKAS'); ------------------------------------6

SELECT * FROM EMPLOYEE_DETAIL_TABLE
WHERE FIRSTNAME LIKE 'A%'; ----------------------------------------7&8


SELECT * FROM EMPLOYEE_DETAIL_TABLE
WHERE FIRSTNAME LIKE '%H'; -----------------------------------------------9


SELECT * FROM EMPLOYEE_DETAIL_TABLE
WHERE FIRSTNAME LIKE 'A%P'; -------------------------------------------10


SELECT * FROM EMPLOYEE_DETAIL_TABLE
WHERE FIRSTNAME <> 'A%P'; -------------------------------11

SELECT * FROM EMPLOYEE_DETAIL_TABLE
WHERE GENDER LIKE '__LE'; ------------------------------12


SELECT * FROM EMPLOYEE_DETAIL_TABLE
WHERE FIRSTNAME LIKE 'A____';-------------------------------------------- 13


SELECT * FROM EMPLOYEE_DETAIL_TABLE
WHERE FIRSTNAME LIKE '%[%]%'; ---------------------------------------------------14

SELECT DISTINCT DEPARTMENT FROM EMPLOYEE_DETAIL_TABLE; ----------------------------------------15

SELECT MAX(SALARY) AS MAX_SALARY FROM EMPLOYEE_DETAIL_TABLE; ------------------------------16

SELECT MIN(SALARY) AS MIN_SALARY FROM EMPLOYEE_DETAIL_TABLE; ------------------------------17

SELECT *, FORMAT(JOINING_DATE, 'dd MMM yyyy') as FORMATTED_JOINING_DATE
FROM EMPLOYEE_DETAIL_TABLE; ------------------------------------- 18

SELECT *, FORMAT(JOINING_DATE, 'yyyy/mm/dd') as FORMATTED_JOINING_DATE
FROM EMPLOYEE_DETAIL_TABLE; ----------------------------------------------19

SELECT *, FORMAT(JOINING_DATE, 'HH:mm:ss') as JOINING_TIME
FROM EMPLOYEE_DETAIL_TABLE; -------------------------------------20

SELECT *, YEAR(JOINING_DATE) as JOINING_YEAR
FROM EMPLOYEE_DETAIL_TABLE; ------------------------------------------21

SELECT *, MONTH(JOINING_DATE) as JOINING_MONTH
FROM EMPLOYEE_DETAIL_TABLE; ------------------------------------------22

SELECT GETDATE() AS SYSTEM_DATE; ------------------------------------------23

SELECT SYSUTCDATETIME() AS CurrentUTCDateTime; ---------------------------24

SELECT FIRSTNAME, GETDATE() AS CURRENTDATE, JOINING_DATE, DATEDIFF(MONTH, JOINING_DATE, GETDATE()) AS MONTH_DIFFERENCE
FROM EMPLOYEE_DETAIL_TABLE; -----------------------------24 A

SELECT FIRSTNAME, GETDATE() AS CURRENTDATE, JOINING_DATE, DATEDIFF(DAY, JOINING_DATE, GETDATE()) AS DAYS_DIFFERENCE
FROM EMPLOYEE_DETAIL_TABLE; -----------------------------25

SELECT * FROM EMPLOYEE_DETAIL_TABLE
WHERE YEAR(JOINING_DATE) = 2013; --------------------------------------26

SELECT * FROM EMPLOYEE_DETAIL_TABLE
WHERE MONTH(JOINING_DATE) = 1; ---------------------------------27 & 28

SELECT COUNT(*) AS EMPLOYEECOUNT
FROM EMPLOYEE_DETAIL_TABLE; ------------------------------29

SELECT TOP 1 * FROM EMPLOYEE_DETAIL_TABLE; ---------------------------------31

SELECT * FROM EMPLOYEE_DETAIL_TABLE
WHERE FIRSTNAME IN ('VIKAS', 'ASHISH', 'NIKHIL'); ---------------------32

SELECT * FROM EMPLOYEE_DETAIL_TABLE
WHERE FIRSTNAME NOT IN ('VIKAS', 'ASHISH', 'NIKHIL'); -----------------------------33

SELECT RTRIM(FIRSTNAME) AS FirstNameWithoutTRAILINGSpaces
FROM EMPLOYEE_DETAIL_TABLE; ----------------------------34

SELECT LTRIM(FIRSTNAME) AS FirstNameWithoutLeadingSpaces
FROM EMPLOYEE_DETAIL_TABLE; ----------------------------35

SELECT 
    FIRSTNAME,
    CASE 
        WHEN Gender = 'Male' THEN 'M'
        WHEN Gender = 'Female' THEN 'F'
        ELSE 'Unknown'
    END AS GenderAbbreviation
FROM 
    EMPLOYEE_DETAIL_TABLE; ----------------------------------36

SELECT CONCAT('Hello ', FIRSTNAME) AS Greeting
FROM EMPLOYEE_DETAIL_TABLE; ----------------------------------37

SELECT * FROM EMPLOYEE_DETAIL_TABLE
WHERE SALARY >600000; ----------------------------38

SELECT * FROM EMPLOYEE_DETAIL_TABLE
WHERE SALARY <700000; ---------------------------------39

SELECT * FROM EMPLOYEE_DETAIL_TABLE
WHERE SALARY BETWEEN 500000 AND 600000; -------------------------------------40

CREATE TABLE PROJECT_DETAIL(
PROJECT_DETAIL_ID INT,
EMPLOYEE_DETAIL_ID INT,
PROJECT_NAME VARCHAR(50))
;

INSERT INTO PROJECT_DETAIL VALUES
(1, 1, 'TASK TRACK'),
(2, 1, 'CLP'),
(3, 1, 'SURVEY MANAGEMENT'),
(4, 2, 'HR MANAGEMENT'),
(5, 3, 'TASK TRACK'),
(6, 3, 'GRS'),
(7, 3, 'DDS'),
(8, 4, 'HR MANAGEMENT'),
(9, 6, 'GL MANAGEMENT') ---------------------------------------------41
;

SELECT * FROM PROJECT_DETAIL;

SELECT DEPARTMENT, SUM(SALARY) AS DEPARTMENT_WISE_TOTAL_SALARY
FROM EMPLOYEE_DETAIL_TABLE
GROUP BY DEPARTMENT; --------------------------------------42

SELECT DEPARTMENT, SUM(SALARY) AS DEPARTMENT_WISE_TOTAL_SALARY
FROM EMPLOYEE_DETAIL_TABLE
GROUP BY DEPARTMENT
ORDER BY DEPARTMENT_WISE_TOTAL_SALARY ASC;-------------------------------------43

SELECT DEPARTMENT, SUM(SALARY) AS DEPARTMENT_WISE_TOTAL_SALARY
FROM EMPLOYEE_DETAIL_TABLE
GROUP BY DEPARTMENT
ORDER BY DEPARTMENT_WISE_TOTAL_SALARY DESC;------------------------------------44

SELECT DEPARTMENT, COUNT(DEPARTMENT) AS DEPARTMENT_COUNT, SUM(SALARY) AS DEPARTMENT_WISE_TOTAL_SALARY
FROM EMPLOYEE_DETAIL_TABLE
GROUP BY DEPARTMENT
ORDER BY DEPARTMENT_WISE_TOTAL_SALARY DESC; ------------------------------45

SELECT DEPARTMENT, AVG(SALARY) AS DEPARTMENT_WISE_AVG_SALARY
FROM EMPLOYEE_DETAIL_TABLE
GROUP BY DEPARTMENT
ORDER BY DEPARTMENT_WISE_AVG_SALARY ASC;-------------------------------46

SELECT DEPARTMENT, MAX(SALARY) AS DEPARTMENT_WISE_MAX_SALARY
FROM EMPLOYEE_DETAIL_TABLE
GROUP BY DEPARTMENT
ORDER BY DEPARTMENT_WISE_MAX_SALARY ASC;-------------------------------------47

SELECT DEPARTMENT, MIN(SALARY) AS DEPARTMENT_WISE_MIN_SALARY
FROM EMPLOYEE_DETAIL_TABLE
GROUP BY DEPARTMENT
ORDER BY DEPARTMENT_WISE_MIN_SALARY ASC;----------------------------------------------48 & 49

SELECT*FROM EMPLOYEE_DETAIL_TABLE;
SELECT*FROM PROJECT_DETAIL;

SELECT *
FROM EMPLOYEE_DETAIL_TABLE A
JOIN PROJECT_DETAIL B ON A.EMPLOYEE_ID = B.EMPLOYEE_DETAIL_ID; -----------------------50

SELECT A.FIRSTNAME, A.LASTNAME ,B.PROJECT_NAME
FROM EMPLOYEE_DETAIL_TABLE A
JOIN PROJECT_DETAIL B ON A.EMPLOYEE_ID = B.EMPLOYEE_DETAIL_ID
ORDER BY A.FIRSTNAME;------------------------------------51

SELECT A.FIRSTNAME, A.LASTNAME, B.PROJECT_NAME
FROM EMPLOYEE_DETAIL_TABLE A
LEFT JOIN PROJECT_DETAIL B ON A.EMPLOYEE_ID = B.EMPLOYEE_DETAIL_ID
ORDER BY FIRSTNAME; --------------------------52

SELECT A.FIRSTNAME, A.LASTNAME, 
COALESCE(B.PROJECT_NAME, '-No Project Assigned') AS PROJECT
FROM EMPLOYEE_DETAIL_TABLE A
LEFT JOIN PROJECT_DETAIL B ON A.EMPLOYEE_ID = B.EMPLOYEE_DETAIL_ID
ORDER BY FIRSTNAME; ----------------------------------53

SELECT B.PROJECT_NAME, A.EMPLOYEE_ID
FROM EMPLOYEE_DETAIL_TABLE A
FULL OUTER JOIN PROJECT_DETAIL B ON A.EMPLOYEE_ID = B.EMPLOYEE_DETAIL_ID
ORDER BY FIRSTNAME; --------------------------54

SELECT A.FIRSTNAME, A.LASTNAME, B.PROJECT_NAME
FROM EMPLOYEE_DETAIL_TABLE A
FULL OUTER JOIN PROJECT_DETAIL B ON A.EMPLOYEE_ID = B.EMPLOYEE_DETAIL_ID
ORDER BY FIRSTNAME; -------------------------------------55 & 56 & 57

SELECT A.FIRSTNAME, A.LASTNAME, B.PROJECT_NAME
FROM PROJECT_DETAIL B
JOIN EMPLOYEE_DETAIL_TABLE A ON A.EMPLOYEE_ID = B.EMPLOYEE_DETAIL_ID
WHERE B.EMPLOYEE_DETAIL_ID IN(
SELECT EMPLOYEE_DETAIL_ID
FROM PROJECT_DETAIL
GROUP BY EMPLOYEE_DETAIL_ID
HAVING COUNT (DISTINCT PROJECT_NAME)>1); -------------------------------58

SELECT A.FIRSTNAME, A.LASTNAME, B.PROJECT_NAME
FROM PROJECT_DETAIL B
JOIN EMPLOYEE_DETAIL_TABLE A ON A.EMPLOYEE_ID = B.EMPLOYEE_DETAIL_ID
WHERE B.PROJECT_NAME IN(
SELECT PROJECT_NAME
FROM PROJECT_DETAIL
GROUP BY PROJECT_NAME
HAVING COUNT (DISTINCT EMPLOYEE_DETAIL_ID)>1);  --------------------------------------59

SELECT * FROM EMPLOYEE_DETAIL_TABLE
CROSS JOIN PROJECT_DETAIL; -------------------------------60





